[package]
name = "todo"
version = "0.1.0"
authors = ["sq5rix <sq5rix@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.97"
serde_derive = "1.0.97"
serde_json = "1.0.40"
app_dirs = "1.2.1"
